### ISSUE TITLE
using the searchProcessor

### ISSUE THREAD

**Issue by kermorgant** [rollerworks/search#139]
Hello,

I've not had time to look at my search since last time I tested the search bundle with a hand crafted search condition.

Now, I've tried to process input from a search form (used the one bundled), but did not succeed to build a search condition. I'm also maybe lacking some string sanitizing as putting a field=value in the textarea  produced error messages.

I've put [my attempt here](https://gist.github.com/kermorgant/eea7e25514a429d3df54d06892416be7)
[and my config](https://gist.github.com/kermorgant/c0cd5659d07b12d5d74b2b5d286d051e)

Sorry to disturb with that, but I feel pretty close and have a hard time figuring out what's wrong...
Regards
Mikael

**Comment by sstok** [comment]
The `exportSearchCondition` method is to export a SearchCondition to human-readable format (like XML).

The the input in the form is a FilterQuery syntax http://rollerworkssearch.readthedocs.io/en/latest/input/filter_query.html (and of course there are errors in the documentation 💀 `=` needs to be `:` ).

I will provide a working code example later today 👍 I haven't time to work on the old documentation.

**Comment by kermorgant** [comment]
Thanks :+1:  I think I filled the form with such a syntax, but have surely done something wrong somewhere...

In fact, I'd be ready to wait a bit and even perhaps integrate alpha code from the v2 as I want to begin with a very simple search form, but I couldn't install the bundle yesterday when I tried (I looked at the error message from composer too briefly, but it seemed to me the "bundle" was yet compatible with the main "search component").

**Comment by sstok** [comment]
This should do the trick (untested).

```php
/**
  * @Route("/recherche", name="recherche")
  * @Method({"GET", "POST"})
  */
 public function searchAction(Request $request)
 {
     $fieldSet = $this->get('rollerworks_search.fieldset_registry')->get('fiches');
     $config = new ProcessorConfig($fieldSet);

     $searchProcessor = $this->get('rollerworks_search.processor.search_processor_factory')
         ->createProcessor($config, 'fiche');

     $searchProcessor->processRequest($request);

     $form = $this->createForm('Rollerworks\Bundle\SearchBundle\Form\Type\SearchFormType', ['filter' => $searchProcessor->exportSearchCondition('filter_query')]);
     $form->handleRequest($request);

     // When the processor receives a "new" concondition redirect with the filter-code.
     if ($searchProcessor->isSubmitted() && $form->isValid()) {
         return $this->redirectToRoute('recherche', ['filter' => $searchProcessor->getSearchCode()]);
     }

     $em = $this->getDoctrine()->getEntityManager();
     $query = $em->createQuery("SELECT f FROM AppBundle\Entity\Fiche AS f");

     // false indicates the condition may not be empty.
     if ($searchProcessor->isValid(false)) {
         $whereBuilder = $this->get('rollerworks_search.doctrine_orm.factory')->createWhereBuilder(
             $query,
             $searchProcessor->getSearchCondition()
         );

          $whereBuilder->setEntityMapping('AppBundle\Entity\Fiche', 'f');

          $whereBuilder = $doctrineOrmFactory->createCacheWhereBuilder($whereBuilder);
          $whereBuilder->setCacheKey($searchProcessor->getSearchCode());
          $whereBuilder->updateQuery(); // will update the query by append ' WHERE '+  the search condition
      }

     $results = $query->getResult();

     return $this->render('services/annuaire.html.twig', [
         'data' => $query->getResult(),
         'search_errors' => $searchProcessor->getErrors(),
         'form' => $form->createView()
     ]);
 }
```

**Comment by kermorgant** [comment]
Hello,

Thanks. well, I tested, but still no search condition generated.

I submitted the form with that data 

`
  rollerworks_search[filter]:name: martin
  rollerworks_search[format]:filter_query
  rollerworks_search[submit]:
  rollerworks_search[_token]:LctIIdvMIw70zz8utovp4T1C4QSFJ1Fq3V75XOePkls
`

after redirection, the url looked like this : http://127.0.0.1:8000/recherche?filter=eJzLS8xNtVLITSwqycyzBgAhdwTC

and this dump gives me a null value
`
var_dump($searchProcessor->getSearchCondition());
`
Anyway, don't bother with that, I can live without it for the moment and can wait for v2.

Thx again

**Comment by sstok** [comment]
Sorry, I did not have time to look into this. I'm making good progress with RollerworksSearch and hope to release 2.0-alpha1 before the end of this month (or before April at least).

**Comment by sstok** [comment]
GREAT NEWS! The first alpha release for v2.0.0 is ready. I will provide will provide a full Symfony powered example tomorrow 👍 

I don't expect to any major API changes, unless there are problems that can only be fixed with a breakage. At least it's now possible to use a "fixed" version.

My main focus for now is updating the documentation, and providing much better examples for framework integration.

**Note:** The Symfony integration bundle depends on Symfony 3.3 which is not released yet.

**Comment by sstok** [comment]
```php
use Rollerworks\Component\Search\Processor\ProcessorConfig;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Acme\Search\FieldSet\FichesFieldSet;

// ...

class SearchController extends Controller
{

    /**
     * @Route("/recherche", name="recherche")
     * @Method({"GET", "POST"})
     */
    public function searchAction(Request $request)
    {
        $fieldSet = $this->get('rollerworks_search.fieldset_registry')->get(FichesFieldSet::class);
        $config = new ProcessorConfig($fieldSet, 'fiche');

        $searchPayload = $this->get('rollerworks_search.search_processor')->processRequest($request, $config);

        // When the processor receives a "new" condition redirect with the filter-code.
        if ($searchPayload->isChanged() && $searchPayload->isValid()) {
            return $this->redirectToRoute('recherche', ['filter' => $searchPayload->searchCode]);
        }

        $em = $this->getDoctrine()->getEntityManager();
        $query = $em->createQuery("SELECT f FROM AppBundle\Entity\Fiche AS f");

        // false indicates the condition may not be empty.
        if (null !== $searchPayload->searchCondition) {
            $doctrineOrmFactory = $this->get('rollerworks_search.doctrine_orm.factory');

            $conditionGenerator = $doctrineOrmFactory->createCachedConditionGenerator(
                $doctrineOrmFactory->createConditionGenerator(
                    $query,
                    $searchPayload->searchCondition
                )
            );

            // Configure the mapping of fields to the DqlCondition
            $conditionGenerator->setDefaultEntity('AppBundle\Entity\Fiche', 'f');
            $conditionGenerator->setField('id', 'id');

            $conditionGenerator->updateQuery(); // will update the query by append ' WHERE '+  the search condition
        }

        return $this->render(
            'services/annuaire.html.twig',
            [
                'data' => $query->getResult(),
                'search_payload' => $searchPayload, // contains errors (if any) and the exported condition
            ]
        );
    }
}

```

The `Acme\Search\FieldSet\FichesFieldSet` must a FieldSetConfigurator like:

```php
use Rollerworks\Component\Search\Extension\Core\Type\IntegerType;
use Rollerworks\Component\Search\Extension\Core\Type\TextType;
use Rollerworks\Component\Search\FieldSetBuilder;
use Rollerworks\Component\Search\FieldSetConfigurator;

final class FichesFieldSet implements FieldSetConfigurator
{
    /**
     * Configure the FieldSet builder.
     *
     * @param FieldSetBuilder $builder
     *
     * @return void
     */
    public function buildFieldSet(FieldSetBuilder $builder)
    {
        $builder->add('id', IntegerType::class);
        $builder->add('name', TextType::class);
    }
}
```

The FieldSetConfigurator is automatically loaded by the FQCN, if there are dependencies you need to register in the Service Container and tag it as an `rollerworks_search.fieldset` (no other attributes required).
