### ISSUE TITLE
[Bundle] error in input_processor.xml service config

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#172]
| Q                     | A
| --------------------- | -----
| Bug report?           | yes
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | no

Symfony 3.3.9.

After having installed:
```
        "rollerworks/search": "^2.0@alpha",
        "rollerworks/search-api-platform": "^0.3",
        "rollerworks/search-bundle": "^2.0@alpha",
        "rollerworks/search-doctrine-dbal": "^2.0@alpha",
        "rollerworks/search-doctrine-orm": "^2.0@alpha",
```

and enabling the bundle, I get an error:
```
Attribute "public" on service "rollerworks_search.input.string_query" cannot be inherited from "defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly.

at XmlFileLoader->parseDefinition(object(DOMElement), '/app/vendor/rollerworks/search-bundle/src/DependencyInjection/../Resources/config/input_processor.xml', array('tags' => array(), 'public' => false))
in XmlFileLoader.php (line 143)
```

**Comment by dkarlovi** [comment]
I've since opened the file and figured out that Symfony validator did not get installed, so I did by hand.

This did not fix the problem, but once I've removed
```
        <defaults public="false" />
```

from the file, it works now. Might be a hint.

**Comment by sstok** [comment]
This should be fixed in the last release of the bundle.
https://github.com/rollerworks/RollerworksSearchBundle/releases/tag/v2.0.0-ALPHA6

Not sure why this release was delayed 😳

**Comment by dkarlovi** [comment]
Thanks! <3

Not related, but would you consider tagging `search-symfony-validator` too? Can only install via commit ID currently.

**Comment by sstok** [comment]
Done 👍
