### ISSUE TITLE
[API Platform] exportedCondition never the same as input because of boolean types

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#177]
| Q                     | A
| --------------------- | -----
| Bug report?           | yes
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | no

Using this code for output:
```php
        var_dump($input['fields']['name']['pattern-matchers'][0]);
        var_dump($payload->exportedCondition['fields']['name']['pattern-matchers'][0]);
        var_dump($input === $payload->exportedCondition);
        exit;
```

If I search for: http://127.0.0.1:8000/api/images?search[fields][name][pattern-matchers][0][type]=CONTAINS&search[fields][name][pattern-matchers][0][value]=Eiffel&search[fields][name][pattern-matchers][0][case-insensitive]=1, I get:

```
array (size=3)
  'type' => string 'CONTAINS' (length=8)
  'value' => string 'Eiffel' (length=6)
  'case-insensitive' => string '1' (length=1)
array (size=3)
  'type' => string 'CONTAINS' (length=8)
  'value' => string 'Eiffel' (length=6)
  'case-insensitive' => boolean true
boolean false
```

If I search for http://127.0.0.1:8000/api/images?search[fields][name][pattern-matchers][0][type]=CONTAINS&search[fields][name][pattern-matchers][0][value]=Eiffel&search[fields][name][pattern-matchers][0][case-insensitive]=0, I get:

```
array (size=3)
  'type' => string 'CONTAINS' (length=8)
  'value' => string 'Eiffel' (length=6)
  'case-insensitive' => string '0' (length=1)
array (size=3)
  'type' => string 'CONTAINS' (length=8)
  'value' => string 'Eiffel' (length=6)
  'case-insensitive' => boolean false
boolean false
```

**ApiSearchProcessor will always think input and generated conditions are non-equal**, resulting in it always redirecting, causing a redirect loop.

**Comment by sstok** [comment]
@dkarlovi Can you check if https://github.com/rollerworks/search-api-platform/pull/6 fixes your problem?
