### ISSUE TITLE
[Doctrine DBAL] add MysqlQueryPlatform

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#178]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

Required to use the feature with MySQL.

**Comment by sstok** [comment]
What exactly isn't working currently? Travis is tested with MySQL, and the QueryPlatform support was recently rewritten as regexp support was removed (_to much of a performance risk and not consistently implemented_).

**Comment by dkarlovi** [comment]
`Rollerworks\Component\Search\Doctrine\Orm\QueryPlatformTrait` is requiring it?

https://github.com/rollerworks/search-doctrine-orm/blob/master/src/QueryPlatformTrait.php#L34-L35

**Comment by dkarlovi** [comment]
BTW, you should really consider a mono-repo for this project. Obviously you'll go the "plugins" route, it's currently quite difficult to navigate across all the cross-cutting projects (demonstrated here).

**Comment by sstok** [comment]
It seems something is wrong with the Travis configuration 🤔 it's running the exact version but it should fail (as I can reproduce this locally!).

A monorep would indeed make this allot easier 😛 but it will be a big challenge to get all the tests working properly (especially for the bundle as it enables integrations by condition). And I'm not sure how I can merge all the commits into one without loosing my HEAD (pun intended 😅).

**Comment by dkarlovi** [comment]
> without loosing my HEAD

Nice. :+1:

**Comment by sstok** [comment]
This should be fixed now, let me know if it still not working 👍

**Comment by dkarlovi** [comment]
It's working, thanks!
