### ISSUE TITLE
Symfony 4 compability

### ISSUE THREAD

**Issue by sstok** [rollerworks/search#180]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

To update/check:

- [x] Search core component - https://github.com/rollerworks/search/pull/181
- [x] search-symfony-validator - https://github.com/rollerworks/search-symfony-validator/pull/11
- [x] search-processor
- [x] search-api-platform - https://github.com/rollerworks/search-api-platform/pull/7
- [x] RollerworksSearchBundle - https://github.com/rollerworks/RollerworksSearchBundle/pull/36
- [ ] search-doctrine-dbal (requires 2.6-beta)
- [ ] search-doctrine-orm (requires 2.6-beta)

**Comment by dkarlovi** [comment]
ORM 2.6 is out, BTW.
