### ISSUE TITLE
[Core] Allow for application-level search condition pre-processing

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#182]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

If your search is user-facing (which it most often is), you'd want to restrict the query before performing the search.

For example, in the e-commerce system, user searches `label: shoes`, but your application want to only search its own orders so it becomes `user: 123; label: shoes`. It probably has other applications too.

I propose to introduce a way to register your callback which will get the opportunity to modify the (normalized, `ArrayInput`?) search condition before the query. In Symfony it would probably be an event, don't know how (or if) to introduce it elsewhere.

**Comment by sstok** [comment]
This is already supported, but not uniformly as (namely Doctrine ORM) needs a rather complex query to make this work with joins.

http://rollerworkssearch.readthedocs.io/en/latest/integration/doctrine/orm.html#querying-the-database

> To prevent certain users from getting results they are not allowed to see you can combine the generated condition with a primary AND-condition.

```php
// Doctrine\ORM\EntityManagerInterface
$entityManager = ...;

// Note. There's no need to add a 'WHERE' at the end of the query as this can be applied later
// An empty SearchCondition produces an empty result, and thus would result in an invalid query.
$query = '
    SELECT
        i
    FROM
        Acme\Entity\User AS u
    LEFT JOIN
        u.contacts AS c
    WHERE
        u.id = :user_id
';

$statement = $entityManager->createQuery($query);
$statement->setParameter('user_id', $id);

// Rollerworks\Component\Search\SearchCondition object
$searchCondition = ...;

$conditionGenerator = $doctrineOrmFactory->createConditionGenerator($statement, $searchCondition);
// ...

$conditionGenerator->updateQuery(' AND '); // note the spaces around the statement

$users = $statement->getResult();
```

To do this for orders you first need to JOIN on the user's table, in order (no pun) to reference the user-id. `SELECT
        o
    FROM
        Acme\Entity\Order AS o
    JOIN
        o.user AS u
    WHERE
        u.id = :user_id`

If you have a better better idea please let me know 👍

**Comment by dkarlovi** [comment]
For Symfony, it might be OK to dispatch a `SearchEvent` with a `SearchCondition` payload. This would allow you to modify it before processing it.

**Comment by sstok** [comment]
I think I have an idea with what your suggesting 😄 I don't like modifying the "SearchCondition's condition" itself for this purpose as it makes caching of processed input more fragile. And limiting the results is an internal detail of the query generator.

But I think should be possible to provide a pre-condition as part of the SearchCondition.

```php
class SearchCondition
{
    private $fieldSet;
    private $values;
    private $pareCondition;

    public function __construct(FieldSet $fieldSet, ValuesGroup $valuesGroup)
    {
        $this->fieldSet = $fieldSet;
        $this->values = $valuesGroup;
    }

    public function getFieldSet(): FieldSet
    {
        return $this->fieldSet;
    }

    public function getValuesGroup(): ValuesGroup
    {
        return $this->values;
    }

    public function setPreCondition(SearchPreCondition $condition): self
    {
        $this->pareCondition = $condition;
    }

    public function getPreCondition(): ?SearchPreCondition
    {
        return $this->pareCondition;
    }

    /**
     * Checks that the FieldSet of this condition is supported
     * by the contexts it's used in.
     *
     * @param \string[] ...$name One or more FieldSet names to check for
     */
    public function assertFieldSetName(string ...$name)
    {
        if (!in_array($providedName = $this->fieldSet->getSetName(), $name, true)) {
            throw new UnsupportedFieldSetException($name, $providedName);
        }
    }
}

final class SearchPreCondition
{
    private $values;

    public function __construct(ValuesGroup $valuesGroup)
    {
        $this->values = $valuesGroup;
    }

    public function getValuesGroup(): ValuesGroup
    {
        return $this->values;
    }
}
```

This reuses the SearchConditon model-format to compose a Condition that is only used for generating a pre-condition in the Query. _This reuses the SearchCondition's FieldSet as providing a separate FieldSet makes asserting a supported FieldSet more complicated. As an alternative some fields can be marked as internal/hidden to disallow usage by InputProcessors._

And it allows to reuse the already existing code for generating Queries 🤘

To apply this PreCondition you need to have some sort of Listener (like the one you suggested).
For the Bundle _and_ API-Platform it indeed will be the easiest to dispatch with a namespaced event to prevent triggering other listeners (great suggestion!).

**Comment by sstok** [comment]
The ApiPlatform now allows to set a pre-condition using an EventListener. 

But Doctrine DBAL/ORM and Elasticsearch? need to be updated.
