### ISSUE TITLE
[Meta] Switch the build process to the newly introduced make-based process

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#193]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | no

As we've introduced the make-based build process in #187, it makes sense to actually use it.

This would require fixing all code style violations (easy), but also all stuff found by PHPStan (hard).

We might go with lowering PHPStan's level to 1, fixing those, raising to 2, fixing those, etc. Incrementally bringing the entire codebase up in quality.

**Comment by sstok** [comment]
I am way a head of you 😄 will open a pull-request later today 👍

**Comment by sstok** [comment]
Resolved by #194
