### ISSUE TITLE
[Elasticsearch] Support for SearchPreCondition

### ISSUE THREAD

**Issue by sstok** [rollerworks/search#210]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

Related to #182, the Elasticsearch integration doesn't support (_handle_) SearchPreCondition yet.

**Comment by dkarlovi** [comment]
Can you roughly outline what would be needed?

**Comment by sstok** [comment]
The PreConditon needs to be applied before the search-condition.
See https://github.com/rollerworks/search/pull/204 for I did it there 👍

Basically the SearchCondition is applied as sub-group, and the pre-condition as the main group.
