### ISSUE TITLE
[Elasticsearch] Switch to using Elastica query builder for the search instead of our own

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#212]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

As Elasticsearch support is using Elastica to access the service anyway (it's a requirement of the package), it would make sense to just use their query builder instead of managing arrays like we do now.

The change should be pretty straightforward: replace hand-rolled implementation in `QueryConditionGenerator` with `Elastica\QueryBuilder`. Tests still all need to pass.

**Comment by sstok** [comment]
Originally I tried to avoid this to prevent coupling to a single implementation, but if you think it's acceptable to use Elastica I trust you on this 👍

**Comment by dkarlovi** [comment]
We should either drop dependency on Elastica for the client or embrace it fully (with the query builder), currently it's at 50% which makes the least sense to me. :smile:

**Comment by sstok** [comment]
I held a quick poll in the Symfony Slack and majority seems to use Elastica, so 👍 from me.

**Comment by dkarlovi** [comment]
> I trust you, just let me run this quick poll though.

:D

(JK)

**Comment by sstok** [comment]
😄 FML 🤷‍♂️
