### ISSUE TITLE
No elasticsearch.xml service definition in bundle

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#213]
| Q                     | A
| --------------------- | -----
| Bug report?           | yes
| Feature request?      | no
| BC Break report?      | ?
| RFC?                  | no

Dunno what happened, must be something when merging back to a mono-repo, but in currently released bundle there's no `elasticsearch.xml` file. :cry:

**Comment by dkarlovi** [comment]
It's there in both this and bundle's RO repo, but not in the tagged source. @sstok if you have any idea, :+1:

**Comment by sstok** [comment]
No idea what went wrong :) I tagged a new release for all repositories. It should be good now 👍

**Comment by dkarlovi** [comment]
Try it tomorrow and close here if it's OK, TYVM! 🏁
