### ISSUE TITLE
[API Platform] SearchCondition = null, no ability to add a precondition from event

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#216]
| Q                     | A
| --------------------- | -----
| Bug report?           | yes
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | no

If the user doesn't send an actual search query, but you still want to add a pre-condition, you should be able to. Currently, the search condition in `SearchConditionEvent` is null and you don't get to attach anything to it.

For example, if my user sends `GET /api/images`, I still want to apply a pre-condition similar to `GET /api/images?which-I'm-allowed-to-actually-get=true` :)

**Comment by dkarlovi** [comment]
How would we proceed here? Obviously, search condition should always be set, even if it's empty. The validation of the search condition should probably happen AFTER the event is processed.

How much of the underlying code does this change, do you think?

**Comment by dkarlovi** [comment]
@sstok sorry to ping you about this, but it's kind of a blocker for me so it be great if you could share your thoughts how to proceed here. :smile: 

For example:

1. we ensure there's always a search condition going into the event
2. we dispatch the event(s) **before** validation
3. after the events, if the condition is still invalid, then we process it as such

Maybe an easy fix would be to allow setting a new condition to the event?

**Comment by sstok** [comment]
@dkarlovi See #218, and sorry for the delay 😉

**Comment by dkarlovi** [comment]
Sorry, didn't mean to make it sound like you need to do something, let alone ASAP, I'd settle for your opinion. :see_no_evil: 

But since you've done the work already, I'll have to take a look. :+1:

**Comment by dkarlovi** [comment]
This works as expected, except https://github.com/rollerworks/search/pull/218#issuecomment-377177125

**Comment by dkarlovi** [comment]
@sstok this can be easily closed if you only change the typehint.

**Comment by sstok** [comment]
See #236 👍
