### ISSUE TITLE
[PreCondition] use "private" fields for preconditions

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#219]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | yes

Currently, you can apply a pre-condition the same the user would a condition.

But, in preconditions, you might want to restrict on fields which are not available to the user. For example, I'm adding a `owned_by_user` field which I wouldn't want my user to be able to fill out. :smile: 

Of course, since I'll `AND` the pre-condition, it will still work as expected, but I'd like to restrict this to never allow some fields to be searched on outside the precondition.

Makes sense?

**Comment by sstok** [comment]
Next on my list 👍 

Make all fields starting with an underscore private eg. `_id`, these can only be used by the PrimaryCondition ( was PreCondition #232 ).

**Comment by sstok** [comment]
Resolved by #234 👍
