### ISSUE TITLE
[Meta] Fix the build process

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#222]
| Q                     | A
| --------------------- | -----
| Bug report?           | yes
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | no

In #221 we found out the dev-side build process (specifically, CS Fixer) is busted. This sadly defeats the purpose of having a dev-side build process in place to begin with. :(

We should try to get it (and keep it) working at all times, it should significantly lower the effort (and discussions in PR) needed to make a contribution.

**Comment by sstok** [comment]
The CI has been switched to GitHub workflow actions. For now the QA returns exit-code 0 in case of an error. Internally both use the same phpqa image.
