### ISSUE TITLE
Auto-tag all interfaces so they end up in the container

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#238]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

With Symfony 4 and auto-wiring, it's possible to auto-tag all classes implementing an interface. We could do that for
- `rollerworks_search.type_extension`
- `rollerworks_search.fieldset`

**Comment by sstok** [comment]
Great idea 👍
