### ISSUE TITLE
Ordering search results

### ISSUE THREAD

**Issue by Toflar** [rollerworks/search#241]
Hey everybody, amazing library!

I'm looking to build something similar to the Jira extended search input field for issues:
![bildschirmfoto 2018-10-19 um 09 30 48](https://user-images.githubusercontent.com/481937/47203795-b3779280-d381-11e8-845f-c88d076fcc4f.png)

It looks like rollerworks/search is already half way there! I can't find a way how to order the search results though. Is it planned to add anything like that? That would be amazing.

**Comment by sstok** [comment]
Originally I did not add this as I wanted to focus on searching, but it would make searching more advanced and would actually simplify things for some of my own projects.

For the Json format this can be done using keys at the root level, but for the string format this will require a custom syntax. Fields are separated by a `;` and a field cannot begin with special character so this would not result any conflicts.

But which syntax would work 😄 `; @id: asc` or `; [id: asc]` ?? (suggestions welcome).

**Comment by Toflar** [comment]
I find the "array"-like notation a bit strange. Also it's more effort to type. I really like `; @id: asc`. It also makes it easy to explain: "Any fieldname prepended by an `@` will be used for sorting.".

So a whole search query could look like so: `field1: value1, value2; field2: value1, value2; @field1 desc`

**Comment by dkarlovi** [comment]
How would it look for multiple fields?

`title: foo; @date desc; @tile asc`

Also, we need to whitelist fields which are to support ordering by, they shouldn't all be supported (maybe in the first draft only).

**Comment by Toflar** [comment]
> How would it look for multiple fields? `title: foo; @date desc; @title asc`

Yes, we're not even forced to have the order by's at the end. You could also write `@date desc; title: foo` although I don't really like the idea of it. I guess it should be forbidden to order first and then search. So if there's still anything after an order by notation that should likely end in an exception.
Again, not for technical reasons but rather for the sake of consistency in e.g. docs etc.

**Comment by dkarlovi** [comment]
> it should be forbidden to order first and then search. So if there's still anything after an order by notation that should likely end in an exception.

I don't think we should consider the exact order of tokens in the input string, TBH. If the search query is valid, it should do a search, even if it's not "pretty" or canonical.

**Comment by dkarlovi** [comment]
We'll probably start working on this for our usage. Do you still feel `@<field>: asc/desc` is a good notation?

**Comment by Toflar** [comment]
Cool! I like the notation, yes. Do you have any concerns with it?

**Comment by dkarlovi** [comment]
No, just curious if you maybe saw other examples somewhere in the meantime.

So an example query might be: `title: ~* paris; @published_at: desc`.

@sstok are there known collisions with anything if we move forward in this way? We would then proceed with implementing sort for Elasticsearch too.

**Comment by dkarlovi** [comment]
So a rough outline of my first PR
1. I'll add `SearchOrder` which will be the value object for the order condition, accepts `ValuesGroup` (just like `SearchPrimaryCondition`)
2. add support in `StringInput` to find and convert it from `@format` to `SearchOrder` format

My next PR will then just enable that for Elasticsearch. Somebody else can support it for Doctrine.

**Comment by sstok** [comment]
> @sstok are there known collisions with anything if we move forward in this way? We would then proceed with implementing sort for Elasticsearch too.

No the `@` sign has no special meaning in the String Input. So please go ahead 👍 I'm a bit under the weather, so will properly review later.

**Comment by Toflar** [comment]
Imho `['ASC', 'DESC']` is a good thing to be able to configure so that one can invent custom sorting keywords but imho these two should be default because in 99% these are going to be the two options you want to provide :)

**Comment by dkarlovi** [comment]
Yes, `addOrder`'s second param would default to `['ASC', 'DESC']`. :+1:

**Comment by sstok** [comment]
👍 for adding a separate method.

**Comment by dkarlovi** [comment]
Going back and forth here, I decided to use existing mechanisms, just prepend the order fields with `@` in the mapping too. This is in line with the current mapping of private fields (prefixed with an underscore) and also allows having a distinct mapping to use when filtering on the field and sorting on it (which is needed for Elasticsearch in some cases).

This should make the changes required for this to work smaller too so it makes sense (to me) either way.

**Comment by dkarlovi** [comment]
Working on this in #255, do you mind taking a look?

**Comment by dkarlovi** [comment]
#255 is ready for review, I'll start working on the Elasticsearch integration to avoid wasting time.
