### ISSUE TITLE
Contextual / runtime params support

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#249]
**Description**  

In my use cases, there exist some use-cases where I want to have the ability to enrich the search with params which are not under user's direct control.

I'll write in Elasticsearch form because that allows me to be more precise, but the feature should probably be supported in core. Also, imagine this is a RESTful API.

# Contextual params in mappings (simple)

If I want to support multi-language, I can have multiple Elasticsearch indices `articles_en`, `articles_hr`, `articles_nl`.

This could be something like

```
Accept-Language: en
GET /api/articles?search=title:apple

Accept-Language: hr
GET /api/articles?search=title:jabuka
```

What I'd do is map it to an Elasticsearch index like this

```
title => /articles_{locale}#title
```

and then (somehow?) inject the `locale` param which is known at runtime only.

It would yield

```
POST /articles_en/_search
{
    query: {
        match: {
            title: apple
        }
    }
}
```

# Contextual params in mappings (advanced)

Variation of the case above: let's say I want each user to be able to only search their own articles. They would send their access token and an identical query, but get different results.

Example usage:

```
Authorization: Bearer user1
GET /api/articles?search=title:apple

Authorization: Bearer user2
GET /api/articles?search=title:apple
```

would yield

```
POST /articles_en/_search
{
    query: {
        match: {
            title: apple,
            user: user1 # (or user2)
        }
    }
}
```

The additional injected condition could either be static (example: `published: true`) or dynamic, like in this case.

This looks a lot like the primary condition thing we already added, but it should only be applied if this specific field is applied too.

# Contextual fields (very advanced)

So, a variation of the previous example: let's say `user1` and `user2` have **different fields** to search against (for example, EVA model).

By creating a `has_child` query (implemented in #248), one user could have access to a specific child structure (since he's the owner) while the other does not at all, so the additional fields are added at runtime.

Example:

```
Authorization: Bearer user1
GET /api/articles?search=note:apple
HTTP 200

Authorization: Bearer user2
GET /api/articles?search=note:apple
HTTP 400 (note param not available at all to this user)
```

Combining all these example, a mapping would look something like this:

```
note => /articles_{locale}#extended>values.values_{user}.note
```

and would yield

```
POST /articles_en/_search
{
    query: {
        has_child: {
            type: extended,
            query: {
               match: {
                   values.values_user1.note: apple
                   user: user1 # (or user2)
            }
        }
    }
}
```

**Example**  

Given in the description.

**Comment by sstok** [comment]
It took me a while to wrap my head around this 😄 but I like the idea.

**Comment by dkarlovi** [comment]
Awesome, I'll continue to work on this in #251.

**Comment by dkarlovi** [comment]
@sstok working on "Contextual fields (very advanced)", it seems to me the only thing missing is to pass a mapping to `FieldSetBuilder::add` in  `FieldSetConfigurator`, if that were possible, everything would work out of the box.

This means we should transfer the mapping from there into the query builder and use that instead of the ones registered, if available.

Does that make sense to you?

**Comment by dkarlovi** [comment]
BTW I found a way to make this work without any other further changes.

Basically, it works by decorating the condition factory to allow registering mappings there, the factory auto-registers them on all conditions which it creates. It's pretty clean and IMO works well enough to use.

I'd like for the factory to have an interface to allow easier decorating, though.
