### ISSUE TITLE
[Elasticsearch] "suggester"-type field

### ISSUE THREAD

**Issue by dkarlovi** [rollerworks/search#254]
**Description**  
Elasticsearch supports [suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html). The obvious usage example would be the [completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html), but other use cases (like "Did you mean") are also available.

The suggester API is not directly related to query API so the integration might be a bit deeper than just an additional field type so this issue can be considered a start of a conversation.

**Example**  
```
/api/tags?search=suggest:wa

[warm, wash, warderobe]
```

**Comment by sstok** [comment]
As this is Elasticsearch specific I wonder if this should be part of the library. As we try to keep things as consistent between backend-storage engines as much as possible.

For PostgreSQL this can be solved using Full Text Search, but as this is performance sensitive it requires a good index is present.

**Comment by sstok** [comment]
I feel this outside the scope of this project, as we mainly focus on abstracting condition based searching. Providing a suggest-only abstraction might be better suited as a separate project as there is less complexity involved with structure.
