### ISSUE TITLE
[Elasticsearch] Purpose of 'options' parameter in prepareQuery

### ISSUE THREAD

**Issue by jkabat** [rollerworks/search#270]
I saw it used for sending custom order field ES options. However I would need to send custom options for any field.

Consider this example:
```php
$generator->registerField('height', 'attributes[].height', [], ['inner_hits' => '_source' => [
    'attributes.height',
]]);
```

When it is used like that nothing happens when constructing ES query.
To make it work, I need to pass options for every prepareProcessedValuesQuery call, eg:
https://github.com/rollerworks/search/blob/master/lib/Elasticsearch/QueryConditionGenerator.php#L242

While it works like expected, following test fails:
Rollerworks\Component\Search\Tests\Elasticsearch\Functional\ConditionGeneratorResultsTest::it_finds_by_customer_note
[has_child] query does not support [_id]

Maybe this mapping has a typo, or I do not understand logic behind it:
https://github.com/rollerworks/search/blob/master/lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php#L244

If it is a typo, I can make a PR. Wdyt @dkarlovi ?

**Comment by dkarlovi** [comment]
It's (currently) used only for conditions, see
https://github.com/rollerworks/search/blob/e5c44d499788f17142378a96240efd59654fc118/lib/Elasticsearch/QueryConditionGenerator.php#L652

# Conditions

The idea behind `$conditions` is to allow additional conditions to be applied to a query, but only if the field is used.

Example from my app:
```xml
                            <attribute name="origin">
                                <attribute name="property">/{prefix}image@{locale}/image#origin.identifier</attribute>
                                <attribute name="conditions">
                                    <attribute>
                                        <attribute name="property">/{prefix}image@{locale}/image#origin.client</attribute>
                                        <attribute name="value">{client_id}</attribute>
                                    </attribute>
                                </attribute>
                            </attribute>
```

# Conditions options

The `$options` part can (currently) be used by conditions to expand the definition in some way. In the example in the test, it should add a hint for sort by `@_id`, but it might also be a typo. TBH don't know why it was added, can you remove it and verify tests pass? I'd expect something to fail somewhere.

**Comment by jkabat** [comment]
Thanks for the explanation and example.

Tests are green with a fix (passing options in every prepareProcessedValuesQuery) and after removing options from customer-comment mapping (because it is not an order field):
https://github.com/rollerworks/search/blob/master/lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php#L244

**Comment by jkabat** [comment]
@dkarlovi would you like me to do a PR for the change?

**Comment by dkarlovi** [comment]
Sure, but we must keep the current behaviour intact since this does allow custom options in conditions.

Maybe we could add a single test which check passing options to conditions is supported, then it's safer to refactor?

**Comment by jkabat** [comment]
Current behavior will not be affected at all.

We will just allow passing options not only for conditions, but for registered fields as well.
