### ISSUE TITLE
Some possibility to have Apache Solr support?

### ISSUE THREAD

**Issue by vinyvicente** [rollerworks/search#275]
Hello guys,

Good library! It has the possibility to have Apache Solr support driver?

**Comment by sstok** [comment]
It should be possible to add support for this, but I have absolutely not experience with Apache Solr.

Secondly are special features supported? Like OR/AND conditions, special value types (range, string matching, comparisons).

If you are able to help with this that would be great, thanks 👍

**Comment by sstok** [comment]
Unless someone is able to help with adding support, I'm closing this for now.
