### ISSUE TITLE
[Feature] Symfony 5 support

### ISSUE THREAD

**Issue by tacman** [rollerworks/search#280]
This library, and the corresponding Symfony Bundle do not yet work with Symfony 5.  Any chance you could update that?  You can also safely drop unsupported versions of Symfony, and may simply want to bump this (and the bundle) to a new version and only support Symfony 4.4 and Symfony 5.x.

Thanks.

**Comment by sstok** [comment]
I tried to work on this but because the test suite depends on the fos/Elasticabundle which is not compatible yet I was unable to fully run the tests.

**Comment by sstok** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1592 this seems to be possible now, will see if I can get it to work.
